// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: pkg/admin_service/pb/admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname string  `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string  `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email     string  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone     string  `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Password  string  `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Blocked   bool    `protobuf:"varint,7,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Wallet    float32 `protobuf:"fixed32,8,opt,name=wallet,proto3" json:"wallet,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *User) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *User) GetWallet() float32 {
	if x != nil {
		return x.Wallet
	}
	return 0
}

type GetAllUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllUsersReq) Reset() {
	*x = GetAllUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersReq) ProtoMessage() {}

func (x *GetAllUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersReq.ProtoReflect.Descriptor instead.
func (*GetAllUsersReq) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{1}
}

type GetAllUsersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users  []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Status int32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetAllUsersRes) Reset() {
	*x = GetAllUsersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRes) ProtoMessage() {}

func (x *GetAllUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRes.ProtoReflect.Descriptor instead.
func (*GetAllUsersRes) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllUsersRes) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetAllUsersRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AdminLoginRes) Reset() {
	*x = AdminLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRes) ProtoMessage() {}

func (x *AdminLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRes.ProtoReflect.Descriptor instead.
func (*AdminLoginRes) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminLoginRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{5}
}

type BlockUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BlockUserReq) Reset() {
	*x = BlockUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserReq) ProtoMessage() {}

func (x *BlockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserReq.ProtoReflect.Descriptor instead.
func (*BlockUserReq) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{6}
}

func (x *BlockUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnBlockUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnBlockUserReq) Reset() {
	*x = UnBlockUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnBlockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnBlockUserReq) ProtoMessage() {}

func (x *UnBlockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnBlockUserReq.ProtoReflect.Descriptor instead.
func (*UnBlockUserReq) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UnBlockUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DashBoardUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalUsers  int32   `protobuf:"varint,1,opt,name=TotalUsers,proto3" json:"TotalUsers,omitempty"`
	BlockedUser []int32 `protobuf:"varint,2,rep,packed,name=BlockedUser,proto3" json:"BlockedUser,omitempty"`
}

func (x *DashBoardUser) Reset() {
	*x = DashBoardUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashBoardUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashBoardUser) ProtoMessage() {}

func (x *DashBoardUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashBoardUser.ProtoReflect.Descriptor instead.
func (*DashBoardUser) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DashBoardUser) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DashBoardUser) GetBlockedUser() []int32 {
	if x != nil {
		return x.BlockedUser
	}
	return nil
}

type DashBoardProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalProducts       int32   `protobuf:"varint,1,opt,name=TotalProducts,proto3" json:"TotalProducts,omitempty"`
	OutofStockProductID []int32 `protobuf:"varint,2,rep,packed,name=OutofStockProductID,proto3" json:"OutofStockProductID,omitempty"`
	LowStockProductsID  []int32 `protobuf:"varint,3,rep,packed,name=LowStockProductsID,proto3" json:"LowStockProductsID,omitempty"`
}

func (x *DashBoardProduct) Reset() {
	*x = DashBoardProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashBoardProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashBoardProduct) ProtoMessage() {}

func (x *DashBoardProduct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashBoardProduct.ProtoReflect.Descriptor instead.
func (*DashBoardProduct) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DashBoardProduct) GetTotalProducts() int32 {
	if x != nil {
		return x.TotalProducts
	}
	return 0
}

func (x *DashBoardProduct) GetOutofStockProductID() []int32 {
	if x != nil {
		return x.OutofStockProductID
	}
	return nil
}

func (x *DashBoardProduct) GetLowStockProductsID() []int32 {
	if x != nil {
		return x.LowStockProductsID
	}
	return nil
}

type DashboardOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveredOrderProducts int32 `protobuf:"varint,1,opt,name=DeliveredOrderProducts,proto3" json:"DeliveredOrderProducts,omitempty"`
	PendingOrderProducts   int32 `protobuf:"varint,2,opt,name=PendingOrderProducts,proto3" json:"PendingOrderProducts,omitempty"`
	CancelledOrderProducts int32 `protobuf:"varint,3,opt,name=CancelledOrderProducts,proto3" json:"CancelledOrderProducts,omitempty"`
	TotalOrderItems        int32 `protobuf:"varint,4,opt,name=TotalOrderItems,proto3" json:"TotalOrderItems,omitempty"`
	TotalOrderQuantity     int32 `protobuf:"varint,5,opt,name=TotalOrderQuantity,proto3" json:"TotalOrderQuantity,omitempty"`
}

func (x *DashboardOrder) Reset() {
	*x = DashboardOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardOrder) ProtoMessage() {}

func (x *DashboardOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardOrder.ProtoReflect.Descriptor instead.
func (*DashboardOrder) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DashboardOrder) GetDeliveredOrderProducts() int32 {
	if x != nil {
		return x.DeliveredOrderProducts
	}
	return 0
}

func (x *DashboardOrder) GetPendingOrderProducts() int32 {
	if x != nil {
		return x.PendingOrderProducts
	}
	return 0
}

func (x *DashboardOrder) GetCancelledOrderProducts() int32 {
	if x != nil {
		return x.CancelledOrderProducts
	}
	return 0
}

func (x *DashboardOrder) GetTotalOrderItems() int32 {
	if x != nil {
		return x.TotalOrderItems
	}
	return 0
}

func (x *DashboardOrder) GetTotalOrderQuantity() int32 {
	if x != nil {
		return x.TotalOrderQuantity
	}
	return 0
}

type DashboardRevenue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodayRevenue float64 `protobuf:"fixed64,1,opt,name=TodayRevenue,proto3" json:"TodayRevenue,omitempty"`
	MonthRevenue float64 `protobuf:"fixed64,2,opt,name=MonthRevenue,proto3" json:"MonthRevenue,omitempty"`
	YearRevenue  float64 `protobuf:"fixed64,3,opt,name=YearRevenue,proto3" json:"YearRevenue,omitempty"`
}

func (x *DashboardRevenue) Reset() {
	*x = DashboardRevenue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRevenue) ProtoMessage() {}

func (x *DashboardRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRevenue.ProtoReflect.Descriptor instead.
func (*DashboardRevenue) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DashboardRevenue) GetTodayRevenue() float64 {
	if x != nil {
		return x.TodayRevenue
	}
	return 0
}

func (x *DashboardRevenue) GetMonthRevenue() float64 {
	if x != nil {
		return x.MonthRevenue
	}
	return 0
}

func (x *DashboardRevenue) GetYearRevenue() float64 {
	if x != nil {
		return x.YearRevenue
	}
	return 0
}

type DashboardAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreditedAmount float64 `protobuf:"fixed64,1,opt,name=CreditedAmount,proto3" json:"CreditedAmount,omitempty"`
	PendingAmount  float64 `protobuf:"fixed64,2,opt,name=PendingAmount,proto3" json:"PendingAmount,omitempty"`
}

func (x *DashboardAmount) Reset() {
	*x = DashboardAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardAmount) ProtoMessage() {}

func (x *DashboardAmount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardAmount.ProtoReflect.Descriptor instead.
func (*DashboardAmount) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{12}
}

func (x *DashboardAmount) GetCreditedAmount() float64 {
	if x != nil {
		return x.CreditedAmount
	}
	return 0
}

func (x *DashboardAmount) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

type DashBoardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DashboardUser    *DashBoardUser    `protobuf:"bytes,1,opt,name=DashboardUser,proto3" json:"DashboardUser,omitempty"`
	DashboardProduct *DashBoardProduct `protobuf:"bytes,2,opt,name=DashboardProduct,proto3" json:"DashboardProduct,omitempty"`
	DashboardOrder   *DashboardOrder   `protobuf:"bytes,3,opt,name=DashboardOrder,proto3" json:"DashboardOrder,omitempty"`
	DashboardRevenue *DashboardRevenue `protobuf:"bytes,4,opt,name=DashboardRevenue,proto3" json:"DashboardRevenue,omitempty"`
	DashboardAmount  *DashboardAmount  `protobuf:"bytes,5,opt,name=DashboardAmount,proto3" json:"DashboardAmount,omitempty"`
}

func (x *DashBoardRes) Reset() {
	*x = DashBoardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashBoardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashBoardRes) ProtoMessage() {}

func (x *DashBoardRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_admin_service_pb_admin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashBoardRes.ProtoReflect.Descriptor instead.
func (*DashBoardRes) Descriptor() ([]byte, []int) {
	return file_pkg_admin_service_pb_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DashBoardRes) GetDashboardUser() *DashBoardUser {
	if x != nil {
		return x.DashboardUser
	}
	return nil
}

func (x *DashBoardRes) GetDashboardProduct() *DashBoardProduct {
	if x != nil {
		return x.DashboardProduct
	}
	return nil
}

func (x *DashBoardRes) GetDashboardOrder() *DashboardOrder {
	if x != nil {
		return x.DashboardOrder
	}
	return nil
}

func (x *DashBoardRes) GetDashboardRevenue() *DashboardRevenue {
	if x != nil {
		return x.DashboardRevenue
	}
	return nil
}

func (x *DashBoardRes) GetDashboardAmount() *DashboardAmount {
	if x != nil {
		return x.DashboardAmount
	}
	return nil
}

var File_pkg_admin_service_pb_admin_proto protoreflect.FileDescriptor

var file_pkg_admin_service_pb_admin_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0xca, 0x01, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x22, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x41, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x1e,
	0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20,
	0x0a, 0x0e, 0x55, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x51, 0x0a, 0x0d, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x9a, 0x01, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x30,
	0x0a, 0x13, 0x4f, 0x75, 0x74, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x13, 0x4f, 0x75, 0x74,
	0x6f, 0x66, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44,
	0x12, 0x2e, 0x0a, 0x12, 0x4c, 0x6f, 0x77, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x49, 0x44, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x12, 0x4c, 0x6f,
	0x77, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x49, 0x44,
	0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x16, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12,
	0x36, 0x0a, 0x16, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x16, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x2e, 0x0a, 0x12, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x7c, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x54, 0x6f, 0x64,
	0x61, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x59, 0x65, 0x61, 0x72, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x59, 0x65, 0x61, 0x72, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x22,
	0x5f, 0x0a, 0x0f, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0d, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xd5, 0x02, 0x0a, 0x0c, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0d,
	0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x43, 0x0a,
	0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x0e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x43, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x52, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa9, 0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x13, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4e,
	0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x55, 0x6e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x55, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x09, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x13, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_admin_service_pb_admin_proto_rawDescOnce sync.Once
	file_pkg_admin_service_pb_admin_proto_rawDescData = file_pkg_admin_service_pb_admin_proto_rawDesc
)

func file_pkg_admin_service_pb_admin_proto_rawDescGZIP() []byte {
	file_pkg_admin_service_pb_admin_proto_rawDescOnce.Do(func() {
		file_pkg_admin_service_pb_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_admin_service_pb_admin_proto_rawDescData)
	})
	return file_pkg_admin_service_pb_admin_proto_rawDescData
}

var file_pkg_admin_service_pb_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_admin_service_pb_admin_proto_goTypes = []interface{}{
	(*User)(nil),             // 0: admin.User
	(*GetAllUsersReq)(nil),   // 1: admin.GetAllUsersReq
	(*GetAllUsersRes)(nil),   // 2: admin.GetAllUsersRes
	(*AdminLoginReq)(nil),    // 3: admin.AdminLoginReq
	(*AdminLoginRes)(nil),    // 4: admin.AdminLoginRes
	(*NoParam)(nil),          // 5: admin.NoParam
	(*BlockUserReq)(nil),     // 6: admin.BlockUserReq
	(*UnBlockUserReq)(nil),   // 7: admin.UnBlockUserReq
	(*DashBoardUser)(nil),    // 8: admin.DashBoardUser
	(*DashBoardProduct)(nil), // 9: admin.DashBoardProduct
	(*DashboardOrder)(nil),   // 10: admin.DashboardOrder
	(*DashboardRevenue)(nil), // 11: admin.DashboardRevenue
	(*DashboardAmount)(nil),  // 12: admin.DashboardAmount
	(*DashBoardRes)(nil),     // 13: admin.DashBoardRes
}
var file_pkg_admin_service_pb_admin_proto_depIdxs = []int32{
	0,  // 0: admin.GetAllUsersRes.users:type_name -> admin.User
	8,  // 1: admin.DashBoardRes.DashboardUser:type_name -> admin.DashBoardUser
	9,  // 2: admin.DashBoardRes.DashboardProduct:type_name -> admin.DashBoardProduct
	10, // 3: admin.DashBoardRes.DashboardOrder:type_name -> admin.DashboardOrder
	11, // 4: admin.DashBoardRes.DashboardRevenue:type_name -> admin.DashboardRevenue
	12, // 5: admin.DashBoardRes.DashboardAmount:type_name -> admin.DashboardAmount
	3,  // 6: admin.AdminService.AdminLogin:input_type -> admin.AdminLoginReq
	1,  // 7: admin.AdminService.GetAllUsers:input_type -> admin.GetAllUsersReq
	6,  // 8: admin.AdminService.BlockUser:input_type -> admin.BlockUserReq
	7,  // 9: admin.AdminService.UnBlockUser:input_type -> admin.UnBlockUserReq
	5,  // 10: admin.AdminService.DashBoard:input_type -> admin.NoParam
	4,  // 11: admin.AdminService.AdminLogin:output_type -> admin.AdminLoginRes
	2,  // 12: admin.AdminService.GetAllUsers:output_type -> admin.GetAllUsersRes
	5,  // 13: admin.AdminService.BlockUser:output_type -> admin.NoParam
	5,  // 14: admin.AdminService.UnBlockUser:output_type -> admin.NoParam
	13, // 15: admin.AdminService.DashBoard:output_type -> admin.DashBoardRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_admin_service_pb_admin_proto_init() }
func file_pkg_admin_service_pb_admin_proto_init() {
	if File_pkg_admin_service_pb_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_admin_service_pb_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUsersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnBlockUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashBoardUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashBoardProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardRevenue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_admin_service_pb_admin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashBoardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_admin_service_pb_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_admin_service_pb_admin_proto_goTypes,
		DependencyIndexes: file_pkg_admin_service_pb_admin_proto_depIdxs,
		MessageInfos:      file_pkg_admin_service_pb_admin_proto_msgTypes,
	}.Build()
	File_pkg_admin_service_pb_admin_proto = out.File
	file_pkg_admin_service_pb_admin_proto_rawDesc = nil
	file_pkg_admin_service_pb_admin_proto_goTypes = nil
	file_pkg_admin_service_pb_admin_proto_depIdxs = nil
}
