// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: pb/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressId int64 `protobuf:"varint,1,opt,name=AddressId,proto3" json:"AddressId,omitempty"`
	PaymentId int64 `protobuf:"varint,2,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *Checkout) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *Checkout) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type ExecutePurchaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string    `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	OrderInput *Checkout `protobuf:"bytes,2,opt,name=OrderInput,proto3" json:"OrderInput,omitempty"`
}

func (x *ExecutePurchaseReq) Reset() {
	*x = ExecutePurchaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePurchaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePurchaseReq) ProtoMessage() {}

func (x *ExecutePurchaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePurchaseReq.ProtoReflect.Descriptor instead.
func (*ExecutePurchaseReq) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutePurchaseReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecutePurchaseReq) GetOrderInput() *Checkout {
	if x != nil {
		return x.OrderInput
	}
	return nil
}

type ExecutePurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId       int64   `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Paymentmthd   string  `protobuf:"bytes,2,opt,name=Paymentmthd,proto3" json:"Paymentmthd,omitempty"`
	TotalAmount   float32 `protobuf:"fixed32,3,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	PaymentStatus string  `protobuf:"bytes,4,opt,name=PaymentStatus,proto3" json:"PaymentStatus,omitempty"`
}

func (x *ExecutePurchaseResponse) Reset() {
	*x = ExecutePurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePurchaseResponse) ProtoMessage() {}

func (x *ExecutePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePurchaseResponse.ProtoReflect.Descriptor instead.
func (*ExecutePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutePurchaseResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ExecutePurchaseResponse) GetPaymentmthd() string {
	if x != nil {
		return x.Paymentmthd
	}
	return ""
}

func (x *ExecutePurchaseResponse) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ExecutePurchaseResponse) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type ExecutePurchaseWalletReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string    `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	OrderInput *Checkout `protobuf:"bytes,2,opt,name=OrderInput,proto3" json:"OrderInput,omitempty"`
}

func (x *ExecutePurchaseWalletReq) Reset() {
	*x = ExecutePurchaseWalletReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePurchaseWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePurchaseWalletReq) ProtoMessage() {}

func (x *ExecutePurchaseWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePurchaseWalletReq.ProtoReflect.Descriptor instead.
func (*ExecutePurchaseWalletReq) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutePurchaseWalletReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecutePurchaseWalletReq) GetOrderInput() *Checkout {
	if x != nil {
		return x.OrderInput
	}
	return nil
}

type ExecutePurchaseWalletRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId       int64   `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Paymentmthd   string  `protobuf:"bytes,2,opt,name=Paymentmthd,proto3" json:"Paymentmthd,omitempty"`
	TotalAmount   float32 `protobuf:"fixed32,3,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	PaymentStatus string  `protobuf:"bytes,4,opt,name=PaymentStatus,proto3" json:"PaymentStatus,omitempty"`
}

func (x *ExecutePurchaseWalletRes) Reset() {
	*x = ExecutePurchaseWalletRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePurchaseWalletRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePurchaseWalletRes) ProtoMessage() {}

func (x *ExecutePurchaseWalletRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePurchaseWalletRes.ProtoReflect.Descriptor instead.
func (*ExecutePurchaseWalletRes) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutePurchaseWalletRes) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ExecutePurchaseWalletRes) GetPaymentmthd() string {
	if x != nil {
		return x.Paymentmthd
	}
	return ""
}

func (x *ExecutePurchaseWalletRes) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ExecutePurchaseWalletRes) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type CheckOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *CheckOutReq) Reset() {
	*x = CheckOutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutReq) ProtoMessage() {}

func (x *CheckOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutReq.ProtoReflect.Descriptor instead.
func (*CheckOutReq) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{5}
}

func (x *CheckOutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Carts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID   int64   `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	ProductName string  `protobuf:"bytes,2,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	Category    string  `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Quantity    int64   `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Price       float32 `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	FinalPrice  float32 `protobuf:"fixed32,6,opt,name=FinalPrice,proto3" json:"FinalPrice,omitempty"`
}

func (x *Carts) Reset() {
	*x = Carts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Carts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carts) ProtoMessage() {}

func (x *Carts) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carts.ProtoReflect.Descriptor instead.
func (*Carts) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{6}
}

func (x *Carts) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *Carts) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Carts) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Carts) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Carts) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Carts) GetFinalPrice() float32 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

type Addresss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HouseName string `protobuf:"bytes,3,opt,name=house_name,json=houseName,proto3" json:"house_name,omitempty"`
	Phone     string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Street    string `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	City      string `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	State     string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Pin       string `protobuf:"bytes,8,opt,name=pin,proto3" json:"pin,omitempty"`
	Status    int64  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Addresss) Reset() {
	*x = Addresss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addresss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresss) ProtoMessage() {}

func (x *Addresss) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresss.ProtoReflect.Descriptor instead.
func (*Addresss) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{7}
}

func (x *Addresss) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Addresss) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Addresss) GetHouseName() string {
	if x != nil {
		return x.HouseName
	}
	return ""
}

func (x *Addresss) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Addresss) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Addresss) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Addresss) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Addresss) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Addresss) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CheckOutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address        []*Addresss `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	Cart           []*Carts    `protobuf:"bytes,2,rep,name=cart,proto3" json:"cart,omitempty"`
	TotalAmount    float32     `protobuf:"fixed32,3,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	DiscountAmount float32     `protobuf:"fixed32,4,opt,name=DiscountAmount,proto3" json:"DiscountAmount,omitempty"`
}

func (x *CheckOutRes) Reset() {
	*x = CheckOutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRes) ProtoMessage() {}

func (x *CheckOutRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRes.ProtoReflect.Descriptor instead.
func (*CheckOutRes) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{8}
}

func (x *CheckOutRes) GetAddress() []*Addresss {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CheckOutRes) GetCart() []*Carts {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *CheckOutRes) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CheckOutRes) GetDiscountAmount() float32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

type ViewUserOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ViewUserOrdersReq) Reset() {
	*x = ViewUserOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewUserOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUserOrdersReq) ProtoMessage() {}

func (x *ViewUserOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUserOrdersReq.ProtoReflect.Descriptor instead.
func (*ViewUserOrdersReq) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{9}
}

func (x *ViewUserOrdersReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OrderDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FinalPrice    float32 `protobuf:"fixed32,2,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	PaymentMethod string  `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentStatus string  `protobuf:"bytes,4,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
}

func (x *OrderDetails) Reset() {
	*x = OrderDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetails) ProtoMessage() {}

func (x *OrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetails.ProtoReflect.Descriptor instead.
func (*OrderDetails) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderDetails) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetails) GetFinalPrice() float32 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *OrderDetails) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderDetails) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type OrderProductDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   uint32  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string  `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	OrderStatus string  `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Quantity    int32   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice  float32 `protobuf:"fixed32,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
}

func (x *OrderProductDetails) Reset() {
	*x = OrderProductDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductDetails) ProtoMessage() {}

func (x *OrderProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductDetails.ProtoReflect.Descriptor instead.
func (*OrderProductDetails) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderProductDetails) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProductDetails) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderProductDetails) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *OrderProductDetails) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderProductDetails) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type ViewUserOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderDetails        *OrderDetails          `protobuf:"bytes,1,opt,name=order_details,json=orderDetails,proto3" json:"order_details,omitempty"`
	OrderProductDetails []*OrderProductDetails `protobuf:"bytes,2,rep,name=order_product_details,json=orderProductDetails,proto3" json:"order_product_details,omitempty"`
}

func (x *ViewUserOrders) Reset() {
	*x = ViewUserOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewUserOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUserOrders) ProtoMessage() {}

func (x *ViewUserOrders) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUserOrders.ProtoReflect.Descriptor instead.
func (*ViewUserOrders) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{12}
}

func (x *ViewUserOrders) GetOrderDetails() *OrderDetails {
	if x != nil {
		return x.OrderDetails
	}
	return nil
}

func (x *ViewUserOrders) GetOrderProductDetails() []*OrderProductDetails {
	if x != nil {
		return x.OrderProductDetails
	}
	return nil
}

type ViewUserOrdersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*ViewUserOrders `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *ViewUserOrdersRes) Reset() {
	*x = ViewUserOrdersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewUserOrdersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUserOrdersRes) ProtoMessage() {}

func (x *ViewUserOrdersRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUserOrdersRes.ProtoReflect.Descriptor instead.
func (*ViewUserOrdersRes) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{13}
}

func (x *ViewUserOrdersRes) GetOrders() []*ViewUserOrders {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	OrderId   string `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{14}
}

func (x *CancelOrderReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CancelOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type CancelOrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelOrderRes) Reset() {
	*x = CancelOrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_order_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRes) ProtoMessage() {}

func (x *CancelOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRes.ProtoReflect.Descriptor instead.
func (*CancelOrderRes) Descriptor() ([]byte, []int) {
	return file_pb_order_proto_rawDescGZIP(), []int{15}
}

var File_pb_order_proto protoreflect.FileDescriptor

var file_pb_order_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x46, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x52, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22,
	0x9d, 0x01, 0x0a, 0x17, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x6d, 0x74, 0x68, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x6d, 0x74, 0x68, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x5b, 0x0a, 0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x29, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x52, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x9e, 0x01, 0x0a,
	0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x74,
	0x68, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x6d, 0x74, 0x68, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x23, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0xb5, 0x01, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x98, 0x01, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x73, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x8e, 0x01, 0x0a,
	0x0e, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x32, 0x0a, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x48, 0x0a, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x13, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x3c, 0x0a,
	0x11, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x5e, 0x0a, 0x0e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x32, 0xbc, 0x02,
	0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42,
	0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x13, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4f, 0x0a, 0x15, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x12,
	0x0c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x0e, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0b, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_order_proto_rawDescOnce sync.Once
	file_pb_order_proto_rawDescData = file_pb_order_proto_rawDesc
)

func file_pb_order_proto_rawDescGZIP() []byte {
	file_pb_order_proto_rawDescOnce.Do(func() {
		file_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_order_proto_rawDescData)
	})
	return file_pb_order_proto_rawDescData
}

var file_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pb_order_proto_goTypes = []interface{}{
	(*Checkout)(nil),                 // 0: Checkout
	(*ExecutePurchaseReq)(nil),       // 1: ExecutePurchaseReq
	(*ExecutePurchaseResponse)(nil),  // 2: ExecutePurchaseResponse
	(*ExecutePurchaseWalletReq)(nil), // 3: ExecutePurchaseWalletReq
	(*ExecutePurchaseWalletRes)(nil), // 4: ExecutePurchaseWalletRes
	(*CheckOutReq)(nil),              // 5: CheckOutReq
	(*Carts)(nil),                    // 6: Carts
	(*Addresss)(nil),                 // 7: Addresss
	(*CheckOutRes)(nil),              // 8: CheckOutRes
	(*ViewUserOrdersReq)(nil),        // 9: ViewUserOrdersReq
	(*OrderDetails)(nil),             // 10: OrderDetails
	(*OrderProductDetails)(nil),      // 11: OrderProductDetails
	(*ViewUserOrders)(nil),           // 12: ViewUserOrders
	(*ViewUserOrdersRes)(nil),        // 13: ViewUserOrdersRes
	(*CancelOrderReq)(nil),           // 14: CancelOrderReq
	(*CancelOrderRes)(nil),           // 15: CancelOrderRes
}
var file_pb_order_proto_depIdxs = []int32{
	0,  // 0: ExecutePurchaseReq.OrderInput:type_name -> Checkout
	0,  // 1: ExecutePurchaseWalletReq.OrderInput:type_name -> Checkout
	7,  // 2: CheckOutRes.address:type_name -> Addresss
	6,  // 3: CheckOutRes.cart:type_name -> Carts
	10, // 4: ViewUserOrders.order_details:type_name -> OrderDetails
	11, // 5: ViewUserOrders.order_product_details:type_name -> OrderProductDetails
	12, // 6: ViewUserOrdersRes.orders:type_name -> ViewUserOrders
	1,  // 7: OrderService.ExecutePurchase:input_type -> ExecutePurchaseReq
	3,  // 8: OrderService.ExecutePurchaseWallet:input_type -> ExecutePurchaseWalletReq
	5,  // 9: OrderService.CheckOut:input_type -> CheckOutReq
	9,  // 10: OrderService.ViewUserOrders:input_type -> ViewUserOrdersReq
	14, // 11: OrderService.CancelOrder:input_type -> CancelOrderReq
	2,  // 12: OrderService.ExecutePurchase:output_type -> ExecutePurchaseResponse
	4,  // 13: OrderService.ExecutePurchaseWallet:output_type -> ExecutePurchaseWalletRes
	8,  // 14: OrderService.CheckOut:output_type -> CheckOutRes
	13, // 15: OrderService.ViewUserOrders:output_type -> ViewUserOrdersRes
	15, // 16: OrderService.CancelOrder:output_type -> CancelOrderRes
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_order_proto_init() }
func file_pb_order_proto_init() {
	if File_pb_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePurchaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePurchaseWalletReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePurchaseWalletRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Carts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addresss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewUserOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderProductDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewUserOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewUserOrdersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_order_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_order_proto_goTypes,
		DependencyIndexes: file_pb_order_proto_depIdxs,
		MessageInfos:      file_pb_order_proto_msgTypes,
	}.Build()
	File_pb_order_proto = out.File
	file_pb_order_proto_rawDesc = nil
	file_pb_order_proto_goTypes = nil
	file_pb_order_proto_depIdxs = nil
}
